import images from "./images.ts";

const booksData = [
    {
        id: 1,
        bookName: "Life of Pi",
        bookCover: images.lifeOfPi,
        rating: 4.6,
        language: "Eng",
        pageNo: 319,
        author: "Yann Martel",
        genre: ["Adventure", "Philosophical"],
        readed: "13k",
        description: "Pi Patel survives a shipwreck and shares a lifeboat with a Bengal tiger. Their extraordinary journey explores faith, survival, and the power of storytelling amidst adversity.",
        backgroundColor: "rgba(255,250,210,0.9)",
        navTintColor: "#000",
        completion: "50%",
        lastRead: "6d 5h"
    },
    {
        id: 2,
        bookName: "The Great Gatsby",
        bookCover: images.theGreatGatsby,
        rating: 4.4,
        language: "Eng",
        pageNo: 180,
        author: "F. Scott Fitzgerald",
        genre: ["Drama", "Classic"],
        readed: "25k",
        description: "A haunting tale of love, wealth, and tragedy in 1920s America, following Jay Gatsby's obsession with Daisy Buchanan, exploring the illusion of the American Dream and social decadence.",
        backgroundColor: "rgba(220,220,220,0.9)",
        navTintColor: "#000",
        completion: "90%",
        lastRead: "6d 4h"
    },
    {
        id: 3,
        bookName: "The Road",
        bookCover: images.theRoad,
        rating: 4.4,
        language: "Eng",
        pageNo: 287,
        author: "Cormac McCarthy",
        genre: ["Dystopian", "Adventure"],
        readed: "11k",
        description: "A father and son journey through a post-apocalyptic landscape, struggling to survive against bleak odds, exploring love, hope, and the enduring human spirit in a devastated world.",
        backgroundColor: "rgba(200,200,200,0.9)",
        navTintColor: "#000",
        completion: "40%",
        lastRead: "3d 4h"
    },
    {
        id: 4,
        bookName: "The Alchemist",
        bookCover: images.theAlchemist,
        rating: 4.8,
        language: "Eng",
        pageNo: 208,
        author: "Paulo Coelho",
        genre: ["Adventure", "Fantasy"],
        readed: "15k",
        description: "A journey to discover one's personal legend unfolds in this timeless tale. Santiago, a shepherd, follows his dreams across deserts, finding treasure and wisdom along the way.",
        backgroundColor: "rgba(230,230,230,0.9)",
        navTintColor: "#000",
        completion: "50%",
        lastRead: "2d 3h"
    },
    {
        id: 5,
        bookName: "To Kill a Mockingbird",
        bookCover: images.toKillAMockingbird,
        rating: 4.9,
        language: "Eng",
        pageNo: 324,
        author: "Harper Lee",
        genre: ["Drama", "Classic"],
        readed: "20k",
        description: "A profound exploration of moral growth, innocence, and injustice set in the racially charged American South, seen through the eyes of young Scout Finch and her brother Jem.",
        backgroundColor: "rgba(245,245,220,0.9)",
        navTintColor: "#000",
        completion: "80%",
        lastRead: "5d 1h"
    },
    {
        id: 6,
        bookName: "1984",
        bookCover: images.nineteenEightyFour,
        rating: 4.7,
        language: "Eng",
        pageNo: 328,
        author: "George Orwell",
        genre: ["Dystopian", "Science Fiction"],
        readed: "18k",
        description: "In a totalitarian regime where individuality is crushed, Winston Smith grapples with oppressive surveillance, conformity, and the quest for freedom in a chilling, dystopian world.",
        backgroundColor: "rgba(210,210,210,0.9)",
        navTintColor: "#000",
        completion: "60%",
        lastRead: "4d 2h"
    },
    {
        id: 7,
        bookName: "Pride and Prejudice",
        bookCover: images.prideAndPrejudice,
        rating: 4.6,
        language: "Eng",
        pageNo: 279,
        author: "Jane Austen",
        genre: ["Romance", "Classic"],
        readed: "16k",
        description: "Set in the 19th century, this classic romantic novel portrays the turbulent relationship between Elizabeth Bennet and Mr. Darcy, highlighting themes of love, class, and societal expectations.",
        backgroundColor: "rgba(255,239,220,0.9)",
        navTintColor: "#000",
        completion: "70%",
        lastRead: "3d 5h"
    },
    {
        id: 8,
        bookName: "The Metropolis",
        bookCover: images.theMetropolist,
        rating: 4.1,
        language: "Eng",
        pageNo: 272,
        author: "Seith Fried",
        genre: ["Adventure", "Drama"],
        readed: "13k",
        description: "In Metropolis, the gleaming city of tomorrow, shadows of despair lurk beneath the surface. A gripping tale of hope, ambition, and the fight for freedom unfolds.",
        backgroundColor: "rgba(247,239,219,0.9)",
        navTintColor: "#000",
        completion: "23%",
        lastRead: "10d 5h"
    },
    {
        id: 9,
        bookName: "Brave New World",
        bookCover: images.braveNewWorld,
        rating: 4.5,
        language: "Eng",
        pageNo: 311,
        author: "Aldous Huxley",
        genre: ["Dystopian", "Science Fiction"],
        readed: "14k",
        description: "A thought-provoking novel depicting a future where humanity is conditioned for stability through technology, exploring themes of individuality, freedom, and the consequences of utopia.",
        backgroundColor: "rgba(240,240,240,0.9)",
        navTintColor: "#000",
        completion: "40%",
        lastRead: "7d 1h"
    },
    {
        id: 10,
        bookName: "The Catcher in the Rye",
        bookCover: images.theCatcherInTheRye,
        rating: 4.2,
        language: "Eng",
        pageNo: 277,
        author: "J.D. Salinger",
        genre: ["Drama", "Classic"],
        readed: "22k",
        description: "A compelling exploration of teenage angst and alienation as Holden Caulfield narrates his experiences in New York City, grappling with authenticity, identity, and growing up.",
        backgroundColor: "rgba(250,250,250,0.9)",
        navTintColor: "#000",
        completion: "30%",
        lastRead: "2d 2h"
    },
    {
        id: 11,
        bookName: "The Hobbit",
        bookCover: images.theHobbit,
        rating: 4.7,
        language: "Eng",
        pageNo: 310,
        author: "J.R.R. Tolkien",
        genre: ["Fantasy", "Adventure"],
        readed: "10k",
        description: "Bilbo Baggins embarks on an unexpected journey with dwarves and a wizard to reclaim treasure from the dragon Smaug, discovering courage and friendship along the way.",
        backgroundColor: "rgba(220,210,190,0.9)",
        navTintColor: "#000",
        completion: "50%",
        lastRead: "8d 2h"
    },
    {
        id: 12,
        bookName: "The Chronicles of Narnia",
        bookCover: images.theChroniclesOfNarnia,
        rating: 4.8,
        language: "Eng",
        pageNo: 768,
        author: "C.S. Lewis",
        genre: ["Fantasy", "Adventure"],
        readed: "15k",
        description: "A captivating series of seven books following the adventures of children in the magical land of Narnia, where they encounter mythical creatures and epic battles between good and evil.",
        backgroundColor: "rgba(150,200,250,0.9)",
        navTintColor: "#000",
        completion: "70%",
        lastRead: "12d 1h"
    },
    {
        id: 13,
        bookName: "The Picture of Dorian Gray",
        bookCover: images.thePictureOfDorianGray,
        rating: 4.5,
        language: "Eng",
        pageNo: 240,
        author: "Oscar Wilde",
        genre: ["Drama", "Classic"],
        readed: "8k",
        description: "A tale of vanity and moral corruption, following Dorian Gray as he remains youthful while his portrait ages, exploring the consequences of indulgence and the pursuit of pleasure.",
        backgroundColor: "rgba(220,200,220,0.9)",
        navTintColor: "#000",
        completion: "40%",
        lastRead: "5d 3h"
    },
    {
        id: 14,
        bookName: "The Bell Jar",
        bookCover: images.theBellJar,
        rating: 4.6,
        language: "Eng",
        pageNo: 288,
        author: "Sylvia Plath",
        genre: ["Drama", "Autobiographical"],
        readed: "11k",
        description: "A semi-autobiographical novel depicting Esther Greenwood's struggles with mental illness, societal expectations, and identity, offering a poignant exploration of the female experience in the 1950s.",
        backgroundColor: "rgba(255,240,200,0.9)",
        navTintColor: "#000",
        completion: "60%",
        lastRead: "3d 2h"
    },
    {
        id: 15,
        bookName: "Moby Dick",
        bookCover: images.mobyDick,
        rating: 4.3,
        language: "Eng",
        pageNo: 585,
        author: "Herman Melville",
        genre: ["Adventure", "Classic"],
        readed: "9k",
        description: "A whaling voyage turns into an obsession as Captain Ahab hunts the elusive white whale, Moby Dick, exploring themes of fate, revenge, and the human condition.",
        backgroundColor: "rgba(210,210,210,0.9)",
        navTintColor: "#000",
        completion: "50%",
        lastRead: "7d 4h"
    },
    {
        id: 16,
        bookName: "Fahrenheit 451",
        bookCover: images.fahrenheit451,
        rating: 4.7,
        language: "Eng",
        pageNo: 158,
        author: "Ray Bradbury",
        genre: ["Dystopian", "Science Fiction"],
        readed: "12k",
        description: "In a future where books are banned, fireman Guy Montag begins to question society's oppressive norms, sparking a journey toward enlightenment and the rediscovery of literature's power.",
        backgroundColor: "rgba(240,220,200,0.9)",
        navTintColor: "#000",
        completion: "30%",
        lastRead: "6d 1h"
    },
    {
        id: 17,
        bookName: "Little Women",
        bookCover: images.littleWomen,
        rating: 4.8,
        language: "Eng",
        pageNo: 759,
        author: "Louisa May Alcott",
        genre: ["Drama", "Classic"],
        readed: "14k",
        description: "The lives and struggles of the four March sisters are chronicled in this timeless tale of love, family, and the pursuit of dreams set in post-Civil War America.",
        backgroundColor: "rgba(255,220,255,0.9)",
        navTintColor: "#000",
        completion: "80%",
        lastRead: "10d 2h"
    },
    {
        id: 18,
        bookName: "The Handmaid's Tale",
        bookCover: images.theHandmaidsTale,
        rating: 4.5,
        language: "Eng",
        pageNo: 311,
        author: "Margaret Atwood",
        genre: ["Dystopian", "Feminism"],
        readed: "17k",
        description: "In a totalitarian regime, Offred narrates her life as a handmaid, exploring themes of female oppression, autonomy, and resistance in a chilling vision of the future.",
        backgroundColor: "rgba(200,250,200,0.9)",
        navTintColor: "#000",
        completion: "40%",
        lastRead: "4d 3h"
    },
    {
        id: 19,
        bookName: "Emma",
        bookCover: images.emma,
        rating: 4.4,
        language: "Eng",
        pageNo: 474,
        author: "Jane Austen",
        genre: ["Romance", "Classic"],
        readed: "9k",
        description: "A charming story of matchmaking gone awry, following the spirited Emma Woodhouse as she navigates relationships and learns the importance of self-awareness and humility.",
        backgroundColor: "rgba(220,255,220,0.9)",
        navTintColor: "#000",
        completion: "70%",
        lastRead: "2d 4h"
    },
    {
        id: 20,
        bookName: "The Kite Runner",
        bookCover: images.theKiteRunner,
        rating: 4.9,
        language: "Eng",
        pageNo: 371,
        author: "Khaled Hosseini",
        genre: ["Drama", "Historical"],
        readed: "22k",
        description: "A powerful tale of friendship and betrayal set against the backdrop of Afghanistan's tumultuous history, exploring themes of redemption, guilt, and the enduring bonds of love.",
        backgroundColor: "rgba(240,200,240,0.9)",
        navTintColor: "#000",
        completion: "80%",
        lastRead: "1d 1h"
    },
    {
        id: 21,
        bookName: "Other Words For Home",
        bookCover: images.otherWordsForHome,
        rating: 4.5,
        language: "Eng",
        pageNo: 341,
        author: "Jasmine Warga",
        genre: ["Romance", "Adventure", "Drama"],
        readed: "12k",
        description: "Jude never thought she’d be leaving her beloved older brother and father behind. Her journey is filled with challenges that test her resilience and identity.",
        backgroundColor: "rgba(240,240,232,0.9)",
        navTintColor: "#000",
        completion: "75%",
        lastRead: "3d 5h"
    },
    {
        id: 22,
        bookName: "The Fault in Our Stars",
        bookCover: images.theFaultInOurStars,
        rating: 4.8,
        language: "Eng",
        pageNo: 313,
        author: "John Green",
        genre: ["Drama", "Young Adult"],
        readed: "18k",
        description: "A poignant love story between two teenagers with cancer, Hazel and Gus, as they navigate the complexities of life, illness, and the beauty of fleeting moments.",
        backgroundColor: "rgba(210,200,250,0.9)",
        navTintColor: "#000",
        completion: "40%",
        lastRead: "3d 3h"
    },
    {
        id: 23,
        bookName: "The Secret Garden",
        bookCover: images.theSecretGarden,
        rating: 4.7,
        language: "Eng",
        pageNo: 331,
        author: "Frances Hodgson Burnett",
        genre: ["Children", "Fantasy"],
        readed: "12k",
        description: "An orphaned girl discovers a hidden garden and transforms her life and those of others around her, revealing themes of friendship, healing, and the magic of nature.",
        backgroundColor: "rgba(240,250,240,0.9)",
        navTintColor: "#000",
        completion: "30%",
        lastRead: "5d 1h"
    },
    {
        id: 24,
        bookName: "The Grapes of Wrath",
        bookCover: images.theGrapesOfWrath,
        rating: 4.3,
        language: "Eng",
        pageNo: 464,
        author: "John Steinbeck",
        genre: ["Drama", "Historical"],
        readed: "14k",
        description: "A powerful portrayal of the plight of Dust Bowl migrants, exploring themes of injustice, survival, and resilience in the face of overwhelming challenges during the Great Depression.",
        backgroundColor: "rgba(220,220,220,0.9)",
        navTintColor: "#000",
        completion: "60%",
        lastRead: "2d 2h"
    },
    {
        id: 25,
        bookName: "A Tale of Two Cities",
        bookCover: images.aTaleOfTwoCities,
        rating: 4.6,
        language: "Eng",
        pageNo: 489,
        author: "Charles Dickens",
        genre: ["Historical", "Classic"],
        readed: "16k",
        description: "Set against the tumult of the French Revolution, this novel intertwines the lives of characters in Paris and London, exploring themes of resurrection, sacrifice, and social justice.",
        backgroundColor: "rgba(250,220,250,0.9)",
        navTintColor: "#000",
        completion: "50%",
        lastRead: "4d 1h"
    },
    {
        id: 26,
        bookName: "The Tiny Dragon",
        bookCover: images.theTinyDragon,
        rating: 3.5,
        language: "Eng",
        pageNo: 110,
        author: "Ana C Bouvier",
        genre: ["Drama", "Adventure", "Romance"],
        readed: "13k",
        description: "This sketchbook for kids is the perfect tool for creativity. Dive into colorful adventures filled with tiny dragons, enchanting landscapes, and imaginative quests that inspire young minds.",
        backgroundColor: "rgba(119,77,143,0.9)",
        navTintColor: "#FFF",
        completion: "10%",
        lastRead: "1d 2h"
    },
    {
        id: 27,
        bookName: "The Road to Character",
        bookCover: images.theRoadToCharacter,
        rating: 4.8,
        language: "Eng",
        pageNo: 258,
        author: "David Brooks",
        genre: ["Non-fiction", "Self-help"],
        readed: "9k",
        description: "A thought-provoking exploration of the importance of character and virtue in personal and societal life, urging readers to cultivate deeper values beyond superficial success.",
        backgroundColor: "rgba(220,250,220,0.9)",
        navTintColor: "#000",
        completion: "60%",
        lastRead: "2d 5h"
    },
    {
        id: 28,
        bookName: "Educated",
        bookCover: images.educated,
        rating: 4.7,
        language: "Eng",
        pageNo: 334,
        author: "Tara Westover",
        genre: ["Memoir", "Autobiography"],
        readed: "13k",
        description: "A memoir recounting the author's journey from growing up in a strict, survivalist family to earning a PhD from Cambridge University, highlighting the transformative power of education.",
        backgroundColor: "rgba(255,220,220,0.9)",
        navTintColor: "#000",
        completion: "70%",
        lastRead: "5d 2h"
    },
    {
        id: 29,
        bookName: "Black Beauty",
        bookCover: images.blackBeauty,
        rating: 4.7,
        language: "Eng",
        pageNo: 240,
        author: "Anna Sewell",
        genre: ["Classic", "Fiction"],
        readed: "15k",
        description: "A compelling narrative from the perspective of a horse, addressing issues of animal welfare and the relationship between horses and humans.",
        backgroundColor: "rgba(255,255,240,0.9)",
        navTintColor: "#000",
        completion: "80%",
        lastRead: "2d 3h"
    },
    {
        id: 30,
        bookName: "Where the Crawdads Sing",
        bookCover: images.whereTheCrawdadsSing,
        rating: 4.8,
        language: "Eng",
        pageNo: 368,
        author: "Delia Owens",
        genre: ["Drama", "Mystery"],
        readed: "20k",
        description: "In the marshes of North Carolina, Kya grows up isolated from society, facing challenges that test her resilience, love, and connection to the natural world amidst mystery.",
        backgroundColor: "rgba(250,240,250,0.9)",
        navTintColor: "#000",
        completion: "80%",
        lastRead: "4d 4h"
    }
];

export default booksData;